// pizza endpoints
export const FETCH_PIZZAS_REQUEST = "FETCH_PIZZAS_REQUEST";
export const FETCH_PIZZAS_SUCCESS = "FETCH_PIZZAS_SUCCESS";
export const FETCH_PIZZAS_ERROR = "FETCH_PIZZAS_ERROR";

export const FETCH_PIZZA_REQUEST = "FETCH_PIZZA_REQUEST";
export const FETCH_PIZZA_SUCCESS = "FETCH_PIZZA_SUCCESS";
export const FETCH_PIZZA_ERROR = "FETCH_PIZZA_ERROR";

export const ADD_PIZZA_REQUEST = "ADD_PIZZA_REQUEST";
export const ADD_PIZZA_SUCCESS = "ADD_PIZZA_SUCCESS";
export const ADD_PIZZA_ERROR = "ADD_PIZZA_ERROR";

export const DELETE_PIZZA_REQUEST = "DELETE_PIZZA_REQUEST";
export const DELETE_PIZZA_SUCCESS = "DELETE_PIZZA_SUCCESS";
export const DELETE_PIZZA_ERROR = "DELETE_PIZZA_ERROR";

export const UPDATE_PIZZA_REQUEST = "UPDATE_PIZZA_REQUEST";
export const UPDATE_PIZZA_SUCCESS = "UPDATE_PIZZA_SUCCESS";
export const UPDATE_PIZZA_ERROR = "UPDATE_PIZZA_ERROR";
